// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZywMrrbtg2u6lNPE4s9fnV6oqurf1_g',
    appId: '1:519067541862:web:a9e85d6799438cb92a68a7',
    messagingSenderId: '519067541862',
    projectId: 'gixa-92d08',
    authDomain: 'gixa-92d08.firebaseapp.com',
    storageBucket: 'gixa-92d08.firebasestorage.app',
    measurementId: 'G-K8P57H0GPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiULuKuzSDD9npRPrdmoKmTj6Sr61nvQQ',
    appId: '1:519067541862:android:29aa4a02d34d42302a68a7',
    messagingSenderId: '519067541862',
    projectId: 'gixa-92d08',
    storageBucket: 'gixa-92d08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCISgmL87lJ2prrPz1c9TeetLb68zZaqKU',
    appId: '1:519067541862:ios:b81402854fc255552a68a7',
    messagingSenderId: '519067541862',
    projectId: 'gixa-92d08',
    storageBucket: 'gixa-92d08.firebasestorage.app',
    iosClientId:
        '519067541862-snp3e41nljn4k4o5o99ev0fvlfdii605.apps.googleusercontent.com',
    iosBundleId: 'com.example.Gixa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCISgmL87lJ2prrPz1c9TeetLb68zZaqKU',
    appId: '1:519067541862:ios:b81402854fc255552a68a7',
    messagingSenderId: '519067541862',
    projectId: 'gixa-92d08',
    storageBucket: 'gixa-92d08.firebasestorage.app',
    iosClientId:
        '519067541862-snp3e41nljn4k4o5o99ev0fvlfdii605.apps.googleusercontent.com',
    iosBundleId: 'com.example.Gixa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmZywMrrbtg2u6lNPE4s9fnV6oqurf1_g',
    appId: '1:519067541862:web:dd5c43281f15f7bf2a68a7',
    messagingSenderId: '519067541862',
    projectId: 'gixa-92d08',
    authDomain: 'gixa-92d08.firebaseapp.com',
    storageBucket: 'gixa-92d08.firebasestorage.app',
    measurementId: 'G-Y0B8Y92MVV',
  );
}
